import type { Hangout, Profile, Reel, Conversation, Message } from "./types";

export const mockProfiles: Profile[] = [
  {
    id: "1",
    display_name: "Ana Silva",
    bio: "Amante de esportes e natureza. Sempre buscando novas aventuras!",
    avatar_url: null,
    location: "Sao Paulo, SP",
    interests: ["esportes", "ao_ar_livre", "gastronomia"],
    reputation_score: 4.8,
    badges: ["Primeiro Role", "Anfitriao Top", "Explorador"],
    created_at: "2025-01-15T10:00:00Z",
  },
  {
    id: "2",
    display_name: "Carlos Santos",
    bio: "Gamer e amante de cultura pop. Vamos jogar?",
    avatar_url: null,
    location: "Rio de Janeiro, RJ",
    interests: ["jogos", "cultura", "festas"],
    reputation_score: 4.5,
    badges: ["Primeiro Role", "Social"],
    created_at: "2025-02-01T10:00:00Z",
  },
  {
    id: "3",
    display_name: "Maria Oliveira",
    bio: "Chef amadora e voluntaria nos finais de semana.",
    avatar_url: null,
    location: "Belo Horizonte, MG",
    interests: ["gastronomia", "voluntariado", "cultura"],
    reputation_score: 4.9,
    badges: ["Primeiro Role", "Coracao Generoso", "Anfitriao Top"],
    created_at: "2025-01-20T10:00:00Z",
  },
  {
    id: "4",
    display_name: "Lucas Pereira",
    bio: "Estudante de engenharia. Adoro fotografia e trilhas.",
    avatar_url: null,
    location: "Curitiba, PR",
    interests: ["estudo", "ao_ar_livre", "cultura"],
    reputation_score: 4.3,
    badges: ["Primeiro Role"],
    created_at: "2025-03-10T10:00:00Z",
  },
];

export const mockHangouts: Hangout[] = [
  {
    id: "1",
    creator_id: "1",
    title: "Futebol no Parque Ibirapuera",
    description: "Partida amistosa de futebol no Ibirapuera. Todos os niveis sao bem-vindos! Tragam agua e roupa confortavel.",
    category: "esportes",
    location: "Parque Ibirapuera, Sao Paulo",
    latitude: -23.5874,
    longitude: -46.6576,
    date: "2026-03-15",
    time: "09:00",
    max_participants: 22,
    current_participants: 14,
    status: "active",
    image_url: null,
    created_at: "2026-02-10T10:00:00Z",
    creator: mockProfiles[0],
  },
  {
    id: "2",
    creator_id: "2",
    title: "Noite de Board Games",
    description: "Venha jogar Catan, Ticket to Ride e muito mais! Temos jogos para todos os gostos. Lanche incluso!",
    category: "jogos",
    location: "Luderia Cafe, Rio de Janeiro",
    latitude: -22.9068,
    longitude: -43.1729,
    date: "2026-03-18",
    time: "19:00",
    max_participants: 12,
    current_participants: 8,
    status: "active",
    image_url: null,
    created_at: "2026-02-12T10:00:00Z",
    creator: mockProfiles[1],
  },
  {
    id: "3",
    creator_id: "3",
    title: "Workshop de Culinaria Mineira",
    description: "Aprenda a fazer pao de queijo, feijao tropeiro e doce de leite com receitas tradicionais de Minas Gerais.",
    category: "gastronomia",
    location: "Espaco Gourmet, Belo Horizonte",
    latitude: -19.9191,
    longitude: -43.9387,
    date: "2026-03-20",
    time: "14:00",
    max_participants: 15,
    current_participants: 15,
    status: "full",
    image_url: null,
    created_at: "2026-02-14T10:00:00Z",
    creator: mockProfiles[2],
  },
  {
    id: "4",
    creator_id: "4",
    title: "Trilha no Parque Tangua",
    description: "Trilha leve de 5km com vista incrivel. Ideal para iniciantes. Vamos aproveitar a natureza!",
    category: "ao_ar_livre",
    location: "Parque Tangua, Curitiba",
    latitude: -25.3844,
    longitude: -49.2903,
    date: "2026-03-22",
    time: "07:00",
    max_participants: 20,
    current_participants: 6,
    status: "active",
    image_url: null,
    created_at: "2026-02-16T10:00:00Z",
    creator: mockProfiles[3],
  },
  {
    id: "5",
    creator_id: "1",
    title: "Visita ao MASP",
    description: "Visita guiada ao Museu de Arte de Sao Paulo. Vamos explorar as exposicoes juntos e conversar sobre arte!",
    category: "cultura",
    location: "MASP, Sao Paulo",
    latitude: -23.5614,
    longitude: -46.6558,
    date: "2026-03-25",
    time: "10:00",
    max_participants: 10,
    current_participants: 4,
    status: "active",
    image_url: null,
    created_at: "2026-02-18T10:00:00Z",
    creator: mockProfiles[0],
  },
  {
    id: "6",
    creator_id: "3",
    title: "Mutirao de Limpeza na Praia",
    description: "Vamos fazer a diferenca! Mutirao para limpar a praia e conscientizar sobre meio ambiente.",
    category: "voluntariado",
    location: "Praia de Copacabana, Rio de Janeiro",
    latitude: -22.9711,
    longitude: -43.1822,
    date: "2026-03-28",
    time: "08:00",
    max_participants: 50,
    current_participants: 23,
    status: "active",
    image_url: null,
    created_at: "2026-02-20T10:00:00Z",
    creator: mockProfiles[2],
  },
];

export const mockReels: Reel[] = [
  {
    id: "1",
    user_id: "1",
    hangout_id: "1",
    media_url: "/images/reel-placeholder-1.jpg",
    media_type: "image",
    caption: "Que jogo incrivel no Ibirapuera! Times muito equilibrados.",
    thumbnail_url: null,
    created_at: "2026-02-15T16:00:00Z",
    profile: mockProfiles[0],
    likes_count: 24,
    comments_count: 5,
    is_liked: false,
  },
  {
    id: "2",
    user_id: "2",
    hangout_id: "2",
    media_url: "/images/reel-placeholder-2.jpg",
    media_type: "image",
    caption: "Noite epica de Catan! Quem sera o proximo campeao?",
    thumbnail_url: null,
    created_at: "2026-02-16T22:00:00Z",
    profile: mockProfiles[1],
    likes_count: 18,
    comments_count: 3,
    is_liked: true,
  },
  {
    id: "3",
    user_id: "3",
    hangout_id: "3",
    media_url: "/images/reel-placeholder-3.jpg",
    media_type: "image",
    caption: "Pao de queijo saindo do forno! Ficou perfeito!",
    thumbnail_url: null,
    created_at: "2026-02-17T15:00:00Z",
    profile: mockProfiles[2],
    likes_count: 42,
    comments_count: 8,
    is_liked: false,
  },
  {
    id: "4",
    user_id: "4",
    hangout_id: "4",
    media_url: "/images/reel-placeholder-4.jpg",
    media_type: "image",
    caption: "A vista do Parque Tangua e simplesmente de tirar o folego!",
    thumbnail_url: null,
    created_at: "2026-02-18T09:00:00Z",
    profile: mockProfiles[3],
    likes_count: 31,
    comments_count: 6,
    is_liked: false,
  },
];

export const mockConversations: Conversation[] = [
  {
    id: "1",
    type: "private",
    created_at: "2026-02-10T10:00:00Z",
    participants: [mockProfiles[0], mockProfiles[1]],
    last_message: {
      id: "m1",
      conversation_id: "1",
      sender_id: "1",
      content: "Vai ter futebol no sabado?",
      created_at: "2026-02-17T14:30:00Z",
    },
  },
  {
    id: "2",
    type: "group",
    created_at: "2026-02-12T10:00:00Z",
    participants: [mockProfiles[0], mockProfiles[1], mockProfiles[2]],
    last_message: {
      id: "m2",
      conversation_id: "2",
      sender_id: "3",
      content: "O workshop vai ser demais!",
      created_at: "2026-02-17T12:15:00Z",
    },
  },
  {
    id: "3",
    type: "private",
    created_at: "2026-02-15T10:00:00Z",
    participants: [mockProfiles[0], mockProfiles[3]],
    last_message: {
      id: "m3",
      conversation_id: "3",
      sender_id: "4",
      content: "Qual trilha voce recomenda pra iniciante?",
      created_at: "2026-02-16T19:45:00Z",
    },
  },
];

export const mockMessages: Message[] = [
  {
    id: "m1",
    conversation_id: "1",
    sender_id: "2",
    content: "E ai, tudo certo pra esse sabado?",
    created_at: "2026-02-17T14:00:00Z",
    sender: mockProfiles[1],
  },
  {
    id: "m2",
    conversation_id: "1",
    sender_id: "1",
    content: "Tudo certo! Chego la as 9h.",
    created_at: "2026-02-17T14:15:00Z",
    sender: mockProfiles[0],
  },
  {
    id: "m3",
    conversation_id: "1",
    sender_id: "2",
    content: "Perfeito! Vou levar a bola.",
    created_at: "2026-02-17T14:20:00Z",
    sender: mockProfiles[1],
  },
  {
    id: "m4",
    conversation_id: "1",
    sender_id: "1",
    content: "Vai ter futebol no sabado?",
    created_at: "2026-02-17T14:30:00Z",
    sender: mockProfiles[0],
  },
];
